"""empty message

Revision ID: 04e7dab3aba1
Revises: 2551f51f1c55
Create Date: 2022-07-24 00:11:19.273432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04e7dab3aba1'
down_revision = '2551f51f1c55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###
