"""empty message

Revision ID: 4052608000b5
Revises: 04e7dab3aba1
Create Date: 2022-07-24 00:30:39.895470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4052608000b5'
down_revision = '04e7dab3aba1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('venues', 'seeking_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('seeking_description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('venues', 'description')
    # ### end Alembic commands ###
