"""empty message

Revision ID: 778f4c4ca234
Revises: 54d3511ee37f
Create Date: 2022-07-27 17:59:09.097841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '778f4c4ca234'
down_revision = '54d3511ee37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'artists', ['name'])
    op.create_unique_constraint(None, 'artists', ['phone'])
    op.create_unique_constraint(None, 'venues', ['name'])
    op.create_unique_constraint(None, 'venues', ['phone'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'venues', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    op.drop_constraint(None, 'artists', type_='unique')
    # ### end Alembic commands ###
