"""empty message

Revision ID: 81263a651d8a
Revises: 4052608000b5
Create Date: 2022-07-24 01:55:13.754889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81263a651d8a'
down_revision = '4052608000b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
