"""empty message

Revision ID: 891841efba68
Revises: e729d68442a5
Create Date: 2022-07-27 07:06:02.192924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891841efba68'
down_revision = 'e729d68442a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'link')
    # ### end Alembic commands ###
