"""empty message

Revision ID: 922efdbf1e93
Revises: 891841efba68
Create Date: 2022-07-27 09:59:34.291849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922efdbf1e93'
down_revision = '891841efba68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
