"""empty message

Revision ID: c60e0971886c
Revises: 1a4bcd15fd47
Create Date: 2022-07-24 03:02:42.920968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60e0971886c'
down_revision = '1a4bcd15fd47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
