"""empty message

Revision ID: c996c35fe067
Revises: c69255a6005c
Create Date: 2022-07-24 09:06:46.099462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c996c35fe067'
down_revision = 'c69255a6005c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.String(), nullable=True))
    op.drop_column('artists', 'website')
    op.add_column('venues', sa.Column('website_link', sa.String(length=120), nullable=True))
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('venues', 'website_link')
    op.add_column('artists', sa.Column('website', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###
